name: my_music_player
description: Flutter Clean Architecture
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Audio Service uchun NOtifikatsion oynalarga murojatni taminlaydi
  audio_service: ^0.18.12

  # Audoni qo'llab quvvatlash uchun
  just_audio: ^0.9.35

  # Service locator
  get_it: ^7.6.4

  # Bloc for state management
  flutter_bloc: ^8.1.3

  # Freezed
  freezed_annotation: ^2.4.1

  # Value equality
  equatable: ^2.0.5

  # Functional programming thingies
  dartz: ^0.10.1

  # Local cache
  shared_preferences: ^2.2.1

  liquid_pull_to_refresh: ^3.0.1
  audio_video_progress_bar: ^2.0.0
  marquee: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Bloc ni kompanentalarini yaratib beradi
  build_runner: ^2.4.6
  freezed: ^2.4.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  # example:

  fonts:
    - family: Orbitation
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
